### ISSUE TITLE
Navigation to first or very last page not available

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#41]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.8
Test date: 24.07.2018
User: roland / no log in / user

Actions: 
"users" or "contexts" -> 
![grafik](https://user-images.githubusercontent.com/14921701/43125017-2402c0e4-8f29-11e8-9819-b2b2d924372d.png)

Observation: If user is on page 4 and clicks on "<<" or ">>", either page 3 or 5 is displayed.

Expected Result: Page one or very last page is displayed.

**Comment by wilhelmfrank** [comment]
The pagination is using an external component ("ngx-pagination": "^3.1.1"), which does not offer this behavior. In order to navigate to the first, respectively to the last page, you have to select the first (1) or the last (79) page number in the page list. The ">>" and "<<" are the same as "prev" and "next". It is only possible to remove the "prev" and "next" labels, which might leverage some confusion.
